---
default: true
MD007: # ul-indent
  indent: 4
MD013: # line-length
  line_length: 400 # 300

# disable due to 'profile/README.md'
MD012: false # no-multiple-blanks
MD033: false # no-inline-html
MD041: false # first-line-heading/first-line-h1

ignores:
  - "Bug.md"
